image: docker:latest

services:
  - docker:dind

stages:
- build

tags:
- linux


before_script:
  - echo "IMG_NAME='poppy-ergo-jr'" > config
  - touch ./stage3/SKIP ./stage4/SKIP
  - rm stage4/EXPORT*


build:
  stage: build
  script:
    - ./build-docker.sh
    - ls -larth deploy/
    - set -e && curl --upload-file `ls deploy/*.zip` https://transfer.sh/
